# Generated by Django 3.1.5 on 2021-01-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='url',
            new_name='raw_url',
        ),
    ]
