# Generated by Django 3.1.5 on 2021-01-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20210119_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='order'),
        ),
    ]
